import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/side-nav";
import localFont from "next/font/local";

const lastica = localFont({
  src: "../public/fonts/Lastica.ttf",
  weight: "400",
  variable: "--font-lastica",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lastica.variable} antialiased`}
      >
        <div className="flex h-screen">
          <main className="flex-1 bg-gray-100 overflow-y-auto md:overflow-hidden">
            {children}
          </main>
          <aside className="w-64 bg-blue-800 text-white">
            <SideNav />
          </aside>
        </div>
      </body>
    </html>
  );
}
